name: grole
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - appdirs=1.4.4
  - certifi=2020.6.20
  - click=7.1.2
  - distlib=0.3.1
  - filelock=3.0.12
  - Flask=1.1.2
  - Flask-SQLAlchemy=2.4.4
  - importlib-metadata=2.0.0
  - itsdangerous=1.1.0
  - Jinja2=2.11.2
  - MarkupSafe=1.1.1
  - mysqlclient=2.0.1
  - pipenv=2020.8.13
  - python-dotenv=0.14.0
  - six=1.15.0
  - SQLAlchemy=1.3.19
  - virtualenv-clone=0.5.4
  - Werkzeug=1.0.1
  - zipp=3.2.0
  - Flask-Cors=3.0.8

